package com.dosebloom.app

import android.content.Context
import android.net.Uri
import org.json.JSONArray
import org.json.JSONObject

object ExportImport {
    fun export(context:Context,uri:Uri){ val db=Db(context); val root=JSONObject(); val profiles=JSONArray(); db.profiles().forEach{profiles.put(it)}; root.put("profiles",profiles); val meds=JSONArray(); db.medicines().forEach{m->meds.put(JSONObject().apply{put("id",m.id);put("name",m.name);put("dose",m.dose);put("unit",m.unit);put("times",JSONArray(m.times));put("startDate",m.startDate);put("endDate",m.endDate);put("note",m.note);put("stock",m.stock);put("lowStock",m.lowStock);put("asNeeded",m.asNeeded);put("profile",m.profile)})}; val ints=JSONArray(); db.intakesBetween("0000-01-01","9999-12-31").forEach{i->ints.put(JSONObject().apply{put("medicineId",i.medicineId);put("date",i.date);put("plannedTime",i.plannedTime);put("actualMillis",i.actualMillis);put("status",i.status)})}; root.put("format",1);root.put("exportedAt",System.currentTimeMillis());root.put("medicines",meds);root.put("intakes",ints); context.contentResolver.openOutputStream(uri)?.use{it.write(root.toString(2).toByteArray())} }
    fun import(context:Context,uri:Uri){ val text=context.contentResolver.openInputStream(uri)?.bufferedReader()?.use{it.readText()}?:return; val root=JSONObject(text); val db=Db(context); val profiles=root.optJSONArray("profiles")?:JSONArray(); for(i in 0 until profiles.length()) db.addProfile(profiles.getString(i)); val map=HashMap<Long,Long>(); val meds=root.getJSONArray("medicines"); for(i in 0 until meds.length()){val o=meds.getJSONObject(i); val old=o.optLong("id",0); val m=Medicine(0,o.getString("name"),o.optString("dose","1"),o.optString("unit","таблетка"),o.getJSONArray("times").let{a->(0 until a.length()).map{a.getString(it)}},o.optString("startDate",Schedule.todayKey()),o.optString("endDate",""),o.optString("note",""),o.optInt("stock",0),o.optInt("lowStock",0),o.optBoolean("asNeeded",false),o.optString("profile","Я")); val existing=db.medicines().firstOrNull{it.name==m.name&&it.profile==m.profile}; val id=if(existing==null)db.insertMedicine(m) else {db.updateMedicine(m.copy(id=existing.id));existing.id};map[old]=id}; val ints=root.optJSONArray("intakes")?:JSONArray();for(i in 0 until ints.length()){val o=ints.getJSONObject(i);val id=map[o.optLong("medicineId",-1)]?:continue;db.addIntake(id,o.getString("date"),o.getString("plannedTime"),o.optString("status","TAKEN"),o.optLong("actualMillis",System.currentTimeMillis()))}}
}
